services:
  db:
    image: postgres:latest
    container_name: chess-app-db
    environment:
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspassword
      POSTGRES_DB: chessdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
